//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDeliveryAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth
    {
        public int auth_ID { get; set; }
        public string c_login { get; set; }
        public string c_password { get; set; }
        public Nullable<int> client_ID { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
