//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDeliveryAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartDeliveryEntities1 : DbContext
    {
        public SmartDeliveryEntities1()
            : base("name=SmartDeliveryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auth> Auth { get; set; }
        public virtual DbSet<Bank_Card> Bank_Card { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Courier> Courier { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Package> Package { get; set; }
        public virtual DbSet<Package_Data> Package_Data { get; set; }
        public virtual DbSet<Personal_Data> Personal_Data { get; set; }
        public virtual DbSet<Receipt> Receipt { get; set; }
        public virtual DbSet<Sender> Sender { get; set; }
    }
}
